/**
 * THE WALKABILITY PROOF, and the determinism proof, over real buildings from the real map.
 *
 * The owner named unreachable spots explicitly, so this suite does not sample-check a couple of
 * hand-made floors: it plans the core for hundreds of the city's own parcels, solves floors up and
 * down each of them, and asserts every walkable tile is reachable from where the player lands. The
 * second half asserts that solving the same floor twice — and solving floor 31 without ever having
 * solved floor 30 — gives byte-identical geometry.
 */
import { describe, expect, it } from 'vitest';
import { BuildingArchitecture } from '../../world/BuildingArchitecture';
import * as THREE from 'three';
import { allBuildings, type GeneratedBuilding } from '../../world/CityGen';
import { allScatteredModels } from '../../world/ModelScatter';
import { MODEL_INDEX } from '../../world/models/catalog';
import { scatterDoorFor } from './doors';
import { buildCore, coreContinuity, LIFT_FROM_STOREYS, type BuildingFacts } from './core';
import { solveFloor } from './floor';

const architecture = new BuildingArchitecture(new THREE.Group());
const facade = new THREE.MeshBasicMaterial();
const roof = new THREE.MeshBasicMaterial();

function factsFor(building: GeneratedBuilding): BuildingFacts | undefined {
  const profile = architecture.plan({
    x: 0, z: 0, width: building.width, depth: building.depth, height: building.height,
    style: building.style, variant: building.variant, facade, roof,
  });
  if (!profile.entrance) return undefined;
  return {
    id: `${Math.round(building.x)}:${Math.round(building.z)}`,
    x: building.x, z: building.z, heading: building.heading,
    width: building.width, depth: building.depth, height: building.height,
    style: building.style, entrance: profile.entrance.kind,
  };
}

/** A wide, deterministic slice of the real city — every 7th parcel that carries a tagged door. */
function sample(limit: number): BuildingFacts[] {
  const out: BuildingFacts[] = [];
  const all = allBuildings();
  for (let i = 0; i < all.length && out.length < limit; i += 7) {
    const facts = factsFor(all[i]!);
    if (facts) out.push(facts);
  }
  return out;
}

/** Up to `each` parcels of EVERY structural family. A citywide stride is dominated by houses and
 *  flats, so on its own it would prove nothing about the works and the villas this pass opened. */
function perFamily(each: number): Map<string, BuildingFacts[]> {
  const out = new Map<string, BuildingFacts[]>();
  for (const building of allBuildings()) {
    const bucket = out.get(building.style) ?? [];
    if (bucket.length >= each) continue;
    const facts = factsFor(building);
    if (!facts) continue;
    bucket.push(facts);
    out.set(building.style, bucket);
  }
  return out;
}

describe('the floorplan solver', () => {
  it('leaves no unreachable spot on any floor of any building it opens', () => {
    const buildings = sample(220);
    expect(buildings.length).toBeGreaterThan(150);
    let floors = 0;
    for (const facts of buildings) {
      const core = buildCore(facts);
      // Ground, one up, one down from the top, and a floor deep in the middle of a tall building —
      // the ones a player actually reaches, plus the one nobody would have generated by hand.
      const indices = [...new Set([0, 1, Math.floor(core.storeys / 2), core.storeys - 1])]
        .filter((index) => index >= 0 && index < core.storeys);
      for (const index of indices) {
        const plan = solveFloor(facts, index, core);
        floors++;
        expect(plan.walkable, `${facts.id} floor ${index} has no floor at all`).toBeGreaterThan(20);
        expect(plan.unreachable, `${facts.id} floor ${index}: ${plan.unreachable} unreachable tiles`).toBe(0);
      }
    }
    expect(floors).toBeGreaterThan(300);
  }, 300000);

  it('gives every room a doorway onto the spine, so every room reaches the core', () => {
    for (const facts of sample(80)) {
      const core = buildCore(facts);
      const plan = solveFloor(facts, 0, core);
      expect(plan.rooms.length, `${facts.id} has no rooms`).toBeGreaterThan(0);
      for (const room of plan.rooms) {
        const wall = plan.walls.find((candidate) => candidate.axis === 'x'
          && candidate.gapWidth !== undefined
          && Math.abs(candidate.gapCentre! - room.doorZ) < 1e-6);
        expect(wall, `${facts.id} room ${room.id} has no doorway`).toBeDefined();
      }
    }
  }, 120000);

  it('keeps the core continuous from the street door to the top storey', () => {
    for (const facts of sample(300)) {
      expect(coreContinuity(buildCore(facts)), facts.id).toBeUndefined();
    }
  }, 120000);

  /**
   * The citywide stride is four-fifths houses and flats, so it would pass happily while every works
   * in the city generated a sealed floor. This walks every family the map zones, up and down.
   */
  it('leaves no unreachable spot in ANY structural family, works and villas included', () => {
    const families = perFamily(30);
    expect(families.size, 'the map stopped zoning a whole family').toBeGreaterThan(5);
    for (const [style, buildings] of families) {
      expect(buildings.length, `${style} has no openable parcels at all`).toBeGreaterThan(0);
      for (const facts of buildings) {
        const core = buildCore(facts);
        const indices = [...new Set([0, 1, core.storeys - 1])].filter((index) => index >= 0 && index < core.storeys);
        for (const index of indices) {
          const plan = solveFloor(facts, index, core);
          expect(plan.rooms.length, `${style} ${facts.id} floor ${index} has no rooms`).toBeGreaterThan(0);
          expect(plan.walkable, `${style} ${facts.id} floor ${index} has no floor at all`).toBeGreaterThan(20);
          expect(plan.unreachable, `${style} ${facts.id} floor ${index}: ${plan.unreachable} unreachable`).toBe(0);
        }
      }
    }
  }, 300000);

  /**
   * AND THE SAME PROOF FOR THE SCATTER PASS, which is most of the buildings outside the CBD and was
   * absent from the first version of this suite. Every model family the catalog opens — a farmhouse,
   * a barn, a spaza, a kerk — solves a floor whose every tile is reachable from the mat.
   */
  it('leaves no unreachable spot in any scattered model family either', () => {
    const perModel = new Map<string, BuildingFacts[]>();
    for (const model of allScatteredModels()) {
      if (!MODEL_INDEX.get(model.name)?.interior) continue;
      const bucket = perModel.get(model.name) ?? [];
      if (bucket.length >= 6) continue;
      const door = scatterDoorFor(model);
      if (!door) continue;
      bucket.push(door.facts);
      perModel.set(model.name, bucket);
    }
    expect(perModel.size, 'the catalog stopped opening whole model families').toBe(32);
    for (const [name, buildings] of perModel) {
      for (const facts of buildings) {
        const core = buildCore(facts);
        expect(coreContinuity(core), `${name} ${facts.id}`).toBeUndefined();
        for (const index of [...new Set([0, core.storeys - 1])]) {
          const plan = solveFloor(facts, index, core);
          expect(plan.rooms.length, `${name} ${facts.id} floor ${index} has no rooms`).toBeGreaterThan(0);
          expect(plan.walkable, `${name} ${facts.id} floor ${index} has no floor at all`).toBeGreaterThan(20);
          expect(plan.unreachable, `${name} ${facts.id} floor ${index}: ${plan.unreachable} unreachable`).toBe(0);
        }
      }
    }
  }, 600000);

  /** A shed must not generate a lounge, and a house must not generate a warehouse bay. */
  it('gives each family its own grammar', () => {
    const families = perFamily(12);
    const works = families.get('industrial') ?? [];
    expect(works.length).toBeGreaterThan(4);
    for (const facts of works) {
      const ground = solveFloor(facts, 0);
      expect(ground.eyebrow).toBe('WORKS');
      expect(ground.rooms.some((room) => room.kind === 'warehouse'), `${facts.id} has no bay`).toBe(true);
      const domestic = new Set(['lounge', 'bedroom', 'kitchen', 'dining', 'bathroom']);
      expect(ground.rooms.some((room) => domestic.has(room.kind)), `${facts.id} put a lounge in a works`).toBe(false);
      expect(ground.props.some((prop) => prop.shape === 'rack'), `${facts.id} has no racking`).toBe(true);
      const core = buildCore(facts);
      if (core.storeys > 1) {
        const up = solveFloor(facts, 1, core);
        expect(up.eyebrow).toBe('MEZZANINE');
      }
    }
    for (const style of ['suburban', 'estate'] as const) {
      for (const facts of families.get(style) ?? []) {
        const ground = solveFloor(facts, 0);
        expect(ground.rooms.some((room) => room.kind === 'warehouse'), `${style} generated a warehouse bay`).toBe(false);
        expect(ground.rooms.some((room) => room.kind === 'lounge'), `${style} ${facts.id} has no living room`).toBe(true);
      }
    }
  }, 300000);

  /**
   * "Entering two houses on the same street should not produce the same lounge." A house is the most
   * common building in this city, so sameness would be the first thing a player noticed.
   */
  it('does not give two houses on the same street the same interior', () => {
    const houses = (perFamily(60).get('suburban') ?? []).slice(0, 40);
    expect(houses.length).toBeGreaterThan(20);
    const signatures = new Set<string>();
    const finishes = new Set<string>();
    for (const facts of houses) {
      const core = buildCore(facts);
      const plan = solveFloor(facts, 0, core);
      finishes.add(core.finish);
      signatures.add([
        plan.rooms.length,
        plan.rooms.map((room) => room.kind).join(','),
        plan.props.length,
        plan.palette.wall.toString(16),
        plan.blurb.length,
      ].join('|'));
    }
    // Not a promise of forty unique houses — a promise that walking into two is not walking into one.
    expect(signatures.size, 'every house on the street is the same house').toBeGreaterThan(houses.length * 0.5);
    expect(finishes.size, 'every house has the same finish').toBeGreaterThan(1);
  }, 300000);

  it('gives a lift to every building tall enough to need one, and a stair to all of them', () => {
    let tall = 0;
    for (const facts of sample(300)) {
      const core = buildCore(facts);
      expect(core.stair.w).toBeGreaterThan(1.5);
      if (core.storeys >= LIFT_FROM_STOREYS) { tall++; expect(core.lift, facts.id).toBeDefined(); }
      else expect(core.lift, facts.id).toBeUndefined();
    }
    expect(tall).toBeGreaterThan(3);
  }, 120000);
});

describe('determinism', () => {
  it('rebuilds the identical floor, second visit and hundredth', () => {
    for (const facts of sample(40)) {
      const core = buildCore(facts);
      for (const index of [0, Math.min(1, core.storeys - 1), core.storeys - 1]) {
        const first = solveFloor(facts, index);
        const again = solveFloor(facts, index);
        expect(again).toEqual(first);
      }
    }
  }, 120000);

  it('generates floor 31 the same whether or not floor 30 was ever generated', () => {
    const tall = sample(400).map(buildCore).find((core) => core.storeys > 32);
    // Not every map has a 32-storey building; when one exists this is the on-demand contract.
    if (!tall) return;
    const facts = sample(400).find((candidate) => buildCore(candidate).id === tall.id)!;
    const cold = solveFloor(facts, 31);
    for (let index = 0; index < 31; index++) solveFloor(facts, index);
    const warm = solveFloor(facts, 31);
    expect(warm).toEqual(cold);
  }, 300000);

  it('does not depend on the order buildings are visited', () => {
    const buildings = sample(12);
    const forwards = buildings.map((facts) => solveFloor(facts, 0));
    const backwards = [...buildings].reverse().map((facts) => solveFloor(facts, 0)).reverse();
    expect(backwards).toEqual(forwards);
  }, 120000);
});
