/**
 * THE WALKABILITY PROOF, and the determinism proof, over real buildings from the real map.
 *
 * The owner named unreachable spots explicitly, so this suite does not sample-check a couple of
 * hand-made floors: it plans the core for hundreds of the city's own parcels, solves floors up and
 * down each of them, and asserts every walkable tile is reachable from where the player lands. The
 * second half asserts that solving the same floor twice — and solving floor 31 without ever having
 * solved floor 30 — gives byte-identical geometry.
 */
import { describe, expect, it } from 'vitest';
import { BuildingArchitecture } from '../../world/BuildingArchitecture';
import * as THREE from 'three';
import { allBuildings, type GeneratedBuilding } from '../../world/CityGen';
import { buildCore, coreContinuity, LIFT_FROM_STOREYS, type BuildingFacts } from './core';
import { solveFloor } from './floor';

const architecture = new BuildingArchitecture(new THREE.Group());
const facade = new THREE.MeshBasicMaterial();
const roof = new THREE.MeshBasicMaterial();

function factsFor(building: GeneratedBuilding): BuildingFacts | undefined {
  const profile = architecture.plan({
    x: 0, z: 0, width: building.width, depth: building.depth, height: building.height,
    style: building.style, variant: building.variant, facade, roof,
  });
  if (!profile.entrance) return undefined;
  return {
    id: `${Math.round(building.x)}:${Math.round(building.z)}`,
    x: building.x, z: building.z, heading: building.heading,
    width: building.width, depth: building.depth, height: building.height,
    style: building.style, entrance: profile.entrance.kind,
  };
}

/** A wide, deterministic slice of the real city — every 7th parcel that carries a tagged door. */
function sample(limit: number): BuildingFacts[] {
  const out: BuildingFacts[] = [];
  const all = allBuildings();
  for (let i = 0; i < all.length && out.length < limit; i += 7) {
    const facts = factsFor(all[i]!);
    if (facts) out.push(facts);
  }
  return out;
}

describe('the floorplan solver', () => {
  it('leaves no unreachable spot on any floor of any building it opens', () => {
    const buildings = sample(220);
    expect(buildings.length).toBeGreaterThan(150);
    let floors = 0;
    for (const facts of buildings) {
      const core = buildCore(facts);
      // Ground, one up, one down from the top, and a floor deep in the middle of a tall building —
      // the ones a player actually reaches, plus the one nobody would have generated by hand.
      const indices = [...new Set([0, 1, Math.floor(core.storeys / 2), core.storeys - 1])]
        .filter((index) => index >= 0 && index < core.storeys);
      for (const index of indices) {
        const plan = solveFloor(facts, index, core);
        floors++;
        expect(plan.walkable, `${facts.id} floor ${index} has no floor at all`).toBeGreaterThan(20);
        expect(plan.unreachable, `${facts.id} floor ${index}: ${plan.unreachable} unreachable tiles`).toBe(0);
      }
    }
    expect(floors).toBeGreaterThan(300);
  }, 300000);

  it('gives every room a doorway onto the spine, so every room reaches the core', () => {
    for (const facts of sample(80)) {
      const core = buildCore(facts);
      const plan = solveFloor(facts, 0, core);
      expect(plan.rooms.length, `${facts.id} has no rooms`).toBeGreaterThan(0);
      for (const room of plan.rooms) {
        const wall = plan.walls.find((candidate) => candidate.axis === 'x'
          && candidate.gapWidth !== undefined
          && Math.abs(candidate.gapCentre! - room.doorZ) < 1e-6);
        expect(wall, `${facts.id} room ${room.id} has no doorway`).toBeDefined();
      }
    }
  }, 120000);

  it('keeps the core continuous from the street door to the top storey', () => {
    for (const facts of sample(300)) {
      expect(coreContinuity(buildCore(facts)), facts.id).toBeUndefined();
    }
  }, 120000);

  it('gives a lift to every building tall enough to need one, and a stair to all of them', () => {
    let tall = 0;
    for (const facts of sample(300)) {
      const core = buildCore(facts);
      expect(core.stair.w).toBeGreaterThan(1.5);
      if (core.storeys >= LIFT_FROM_STOREYS) { tall++; expect(core.lift, facts.id).toBeDefined(); }
      else expect(core.lift, facts.id).toBeUndefined();
    }
    expect(tall).toBeGreaterThan(3);
  }, 120000);
});

describe('determinism', () => {
  it('rebuilds the identical floor, second visit and hundredth', () => {
    for (const facts of sample(40)) {
      const core = buildCore(facts);
      for (const index of [0, Math.min(1, core.storeys - 1), core.storeys - 1]) {
        const first = solveFloor(facts, index);
        const again = solveFloor(facts, index);
        expect(again).toEqual(first);
      }
    }
  }, 120000);

  it('generates floor 31 the same whether or not floor 30 was ever generated', () => {
    const tall = sample(400).map(buildCore).find((core) => core.storeys > 32);
    // Not every map has a 32-storey building; when one exists this is the on-demand contract.
    if (!tall) return;
    const facts = sample(400).find((candidate) => buildCore(candidate).id === tall.id)!;
    const cold = solveFloor(facts, 31);
    for (let index = 0; index < 31; index++) solveFloor(facts, index);
    const warm = solveFloor(facts, 31);
    expect(warm).toEqual(cold);
  }, 300000);

  it('does not depend on the order buildings are visited', () => {
    const buildings = sample(12);
    const forwards = buildings.map((facts) => solveFloor(facts, 0));
    const backwards = [...buildings].reverse().map((facts) => solveFloor(facts, 0)).reverse();
    expect(backwards).toEqual(forwards);
  }, 120000);
});
